import 'package:cloud_firestore/cloud_firestore.dart' show Timestamp;
import 'package:suefery/models/order_status.dart';
import 'order_item.dart';

  // Represents the full structured order generated by the S1 AI
class StructuredOrder{
  final DateTime? createdAt;
  final String orderId;
  final String customerId;
  final String partnerStoreName;
  final double estimatedTotal; // total order value
  final String deliveryAddress; 
  final OrderStatus status; // New, Assigned, Delivered, Cancelled
  final double progress; // 0.0 to 1.0 for tracking
  final String? riderId;
  final List<OrderItem> items;
  final bool isConfirmed;
  final DateTime? finishedAt;
  final String? notes;
   
  StructuredOrder({
    this.createdAt,
    required this.orderId,
    required this.customerId,
    required this.partnerStoreName,
    required this.estimatedTotal,
    required this.deliveryAddress,
    required this.status,
    required this.progress,
    required this.riderId,
    required this.items,
    this.isConfirmed = false,
    this.finishedAt,
    this.notes
  });
    @override
  List<Object?> get props => [
    createdAt,
    orderId,
    customerId,
    partnerStoreName,
    estimatedTotal,
    deliveryAddress,
    status,
    progress,
    riderId,
    items,
    isConfirmed,
    finishedAt,
    notes
  ];
  
  //@override
  Map<String, dynamic> toMap()=> {
      'createdAt':Timestamp.fromDate(createdAt!),
      'orderId':orderId,
      'customerId': customerId,
      'partnerStoreName':partnerStoreName,
      'estimatedTotal': estimatedTotal,
      'deliveryAddress':deliveryAddress,
      'status':status,
      'progress':progress,
      'riderId':riderId,
      'items':items,
      'isConfirmed':isConfirmed,
      'finishedAt':finishedAt,
      'notes':notes
    };

  @override
  factory StructuredOrder.fromMap(Map<dynamic, dynamic> data) => StructuredOrder(
      createdAt: (data['createdAt'] as Timestamp).toDate(),
      orderId:data['orderId'],
      customerId: data['customerId'] ?? '',
      partnerStoreName: data['partnerStoreName'] ?? '',
      estimatedTotal : data['estimatedTotal'] ??0,
      deliveryAddress: data['deliveryAddress'] ?? '',
      status: data['status'] ?? OrderStatus.New,
      progress: data['progress'] ?? 0,
      riderId: data['riderId'] ?? '',
      items: List<OrderItem>.from(data['items'] ?? []),
      isConfirmed: data['isConfirmed'] ?? false,
      finishedAt: (data['finishedAt'] as Timestamp).toDate(),
      notes:  data['notes'] ??'',
      );


  double get subtotal => items.fold(0.0, (sum, item) => sum + item.totalPrice);
  double get estimatedDeliveryFee => 5.0; // Mock fee
  double get grandTotal => subtotal + estimatedDeliveryFee;
}