import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'dart:convert';
import 'dart:async';
import '../../data/repositories/i_gemini_repo.dart';
import 'package:http/http.dart' as http;

import '../../data/services/logging_service.dart';


class GeminiRepo1{
  late final GenerativeModel _model;
  late final GenerativeModel _embeddingModel; // Add this line

  GeminiRepo1(){
    //Max Output Tokens: A token roughly equates to four characters. The "Max output tokens" setting defines the upper limit of tokens the response can generate. For instance, a limit of 100 tokens might produce approximately 60-80 words.
    // Temperature: This parameter influences the randomness of token selection. A lower temperature setting suits prompts needing more deterministic or specific responses. In contrast, a higher temperature can foster more varied or imaginative outputs.
    // TopK: Setting topK to 1 means the model chooses the most probable token from its vocabulary for the next token (greedy decoding). A topK of 3, however, allows the model to pick the next token from the three most probable options, based on the temperature setting.
    // TopP: This parameter enables token selection starting from the most probable, accumulating until the sum of probabilities reaches the topP threshold. For example, with tokens A, B, and C having probabilities of 0.3, 0.2, and 0.1, respectively, and a topP value of 0.5, the model will choose either A or B for the next token, utilizing the temperature setting, and exclude C from consideration.
    // Candidate Count: Specifies the maximum number of unique responses to generate. A candidate count of 2 means the model will provide two distinct response options.
    // Stop Sequences: You can specify some sequences of characters whose appearance in the output stops the API from generating a further answer. Let’s say we specify that we include the word “END” in the stop sequences. If the hypothetical result generated by the LLM would be “START MIDDLE END TERMINATE” without the sequence, after adding the sequence, it would turn to “START MIDDLE.”
    final String systemInstructions =  """
    You are the **Suefery** AI Shopping Assistant for a delivery service operating in Beni Suef, Egypt. 
    Your role is to process user messages, extract a confirmed order list, and present it back to the user for confirmation. 
    
    1. CONVERSATION: If the user is just chatting or asking general questions, respond naturally (set confirmed=false).
    2. ORDER PARSING: If the user expresses a clear intent to order items, parse the request into a list of items with quantities and notes.
    3. JSON OUTPUT: ALWAYS respond with a JSON object containing two keys:
        - "ai_response_text": A friendly, localized conversational response to the user.
        - "parsed_order": An object matching the ParsedOrder structure.
        
    ParsedOrder JSON Structure:
    {
      "order_confirmed": true | false,
      "requested_items": [
        { "item_name": "string", "quantity": number, "notes": "string (e.g., brand, size, color)" }
      ]
    }
    
    If the user's intent is clear enough to form an order, set "order_confirmed" to true.
    
    Example for "I need 2 bottles of large coke and 1 bag of Lays chips, spicy flavor":
    
    {
      "ai_response_text": "Great! I've prepared your Suefery order for confirmation. You requested 2 items: 2 large Cokes and 1 bag of spicy Lays chips. Does this look correct?",
      "parsed_order": {
        "order_confirmed": true,
        "requested_items": [
          { "item_name": "Large Coca-Cola bottle", "quantity": 2, "notes": "Large size" },
          { "item_name": "Lays Chips", "quantity": 1, "notes": "Spicy flavor" }
        ]
      }
    }
    """;
    // function declarations

    // final addWorkplaceIncident = FunctionDeclaration(
    //           "addWorkplaceIncident",
    //           "adds reported health and safety incidents , near misses, or other unsafe events",
    //           Schema(
    //             SchemaType.object,
    //             enumValues: [],
    //             requiredProperties: ["createdAt", "details", "location"],
    //             properties: {
    //               "createdById": Schema(SchemaType.string),
    //               "createdAt": Schema(SchemaType.string),
    //               "details": Schema(SchemaType.string),
    //               "location": Schema(SchemaType.string,enumValues: locations),
    //               "locationExtra": Schema(SchemaType.string),
    //               "incidentType": Schema(SchemaType.string),
    //               "incidentTypeExtra": Schema(SchemaType.string),
    //             },
    //           ),
    //         );
    

    _model = GenerativeModel(
      model: 'gemini-2.0-flash', 
      apiKey: dotenv.env['geminiApiKey']!,
      generationConfig: GenerationConfig(
        temperature: 1,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 8192,
        responseMimeType: 'text/plain',
      ),
      systemInstruction: Content.system(systemInstructions),
      tools: [
        Tool(
          //functionDeclarations: [addWorkplaceIncident,addWorkplaceHazard],
        ),
      ],
    );
    _embeddingModel = GenerativeModel(
      model: 'embedding-001', // Correct model name for embeddings
      apiKey: dotenv.env['geminiApiKey']!,
    );
  }

  GenerativeModel  get model => _model;
  GenerativeModel get embeddingModel => _embeddingModel;
}



// IMPORTANT: This API key must be blank for the Canvas environment to provide the token.
const String apiKey = "";
const String apiUrl =
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=$apiKey";

class GeminiRepo implements IGeminiRepo {
  final log = LoggerRepo('GeminiRepo');
  @override
  Future<Map<String, dynamic>> generateContent(
      Map<String, dynamic> payload) async {
    try {
      final http.Response response = await _fetchWithRetry(apiUrl, {
        'method': 'POST',
        'headers': {'Content-Type': 'application/json'},
        'body': jsonEncode(payload),
      });

      if (response.statusCode == 200) {
        final result = jsonDecode(response.body);
        // Extract the JSON text string from the model's output
        final jsonText =
            result['candidates']?[0]['content']?['parts']?[0]?['text'];
        if (jsonText != null) {
          // Decode the nested JSON string into a Map
          return jsonDecode(jsonText);
        } else {
          log.e('API Error: Could not find text part in response.');
          throw Exception('Failed to parse AI response.');
        }
      } else {
        log.e('API Error: Received status code ${response.statusCode}');
        throw Exception('Failed to get response from AI.');
      }
    } catch (e) {
      log.e('API Error: $e');
      rethrow; // Rethrow the exception to be handled by the service
    }
  }
  @override
  Future<String> generateText(
      {required String prompt, List<Map<String, dynamic>>? history}) async {
        
    // Build a simple history if one is provided
    final contents = history ?? [];
    // Add the new user prompt
    contents.add({
      'role': 'user',
      'parts': [{'text': prompt}]
    });
        
    final payload = {
      'contents': contents,
      // NO systemInstruction or responseSchema is needed for this simple call
    };

    try {
      final http.Response response = await _fetchWithRetry(apiUrl, {
        'method': 'POST',
        'headers': {'Content-Type': 'application/json'},
        'body': jsonEncode(payload),
      });

      if (response.statusCode == 200) {
        final result = jsonDecode(response.body);
        final text =
            result['candidates']?[0]['content']?['parts']?[0]?['text'];
        if (text != null) {
          return text;
        } else {
          log.e('Could not find text part in response.');
          throw Exception('Failed to parse AI response.');
        }
      } else {
        log.e('Received status code ${response.statusCode}');
        throw Exception('Failed to get response from AI.');
      }
    } catch (e) {
      log.e('$e');
      rethrow;
    }
  }
  /// Simple fetch retry mechanism
  Future<http.Response> _fetchWithRetry(
    String url,
    Map<String, dynamic> options, {
    int retries = 3,
    Duration delay = const Duration(seconds: 2),
  }) async {
    for (int i = 0; i < retries; i++) {
      try {
        final uri = Uri.parse(url);
        final headers = (options['headers'] as Map<String, String>?) ?? {};
        final body = options['body'];

        final response = await http
            .post(
              uri,
              headers: headers,
              body: body,
            )
            .timeout(const Duration(seconds: 15));

        // Success, or a client error that shouldn't be retried
        if (response.statusCode < 500 && response.statusCode != 429) {
          return response;
        }

        log.e(
            'Attempt ${i + 1} failed with status ${response.statusCode}. Retrying in ${delay.inSeconds}s...');
      } catch (e) {
        log.e(
            'Attempt ${i + 1} failed with exception: $e. Retrying in ${delay.inSeconds}s...');
      }

      // Wait before the next retry
      await Future.delayed(delay);
    }
    // If all retries fail, throw an exception.
    throw Exception('Failed to fetch data from $url after $retries retries.');
  }
}